# Generated by Django 6.1.1 on 2026-09-16 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('NOTIFIED', 'Notified'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='donors.donorprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='blood_requests.bloodrequest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('request', 'donor'), name='unique_request_donor_match')],
            },
        ),
    ]
